# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170220_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
